### PR TITLE
Merge glyphs-3 branch

### PR DESCRIPTION
**Pull request by khaledhosny**
I don’t know why this is not in master already, but the plugin does not work on Apple silicon without it.

### CODE REVIEW

**Comment by florianpircher** [comment]
I believe the `master` branch is for Glyphs 2 and that runs under “Rosetta” on Apple Silicon.

This also means that the latest changes have that landed on `master` and not the `glyphs-3` branch are not available yet when downloading/updating the plugin from Glyphs 3. Maybe it makes sense to switch the repository settings to use the `glyphs-3` branch by default.

**Comment by khaledhosny** [comment]
So, should I close this branch and instead merge master changes into glyphs-3 branch? (there are other changes in master before my PRs).

**Comment by khaledhosny** [comment]
The master branch already works for Glyphs 3 on Intel machines, it does not work on Apple silicon (Glyphs reports an issue about missing version for the current architecture and fails to load the plugin).

It does seem to work with Glyphs 2, though. After installing the plugin manually, Glyphs 2 asked to install Python 2 as well, after installing that it failed to open unless I force starting without plugins. If the plugin already does not work with Glyphs 2, then there is not point in maintaining a different branch for Glyphs 3 support. My testing might be flawed though, as I haven’t used Glyphs 2 for a while (I was surprised that I still have it installed), so may be my installation is broken dependent of the plugin.

**Comment by florianpircher** [comment]
> It does seem to work with Glyphs 2, though.

I assume you meant the opposite. macOS no longer ships with Python, pyobjc, etc. which now needs to be installed manually for Glyphs 2 to run with plugins. There is a tutorial on the Glyphs site.

**Comment by khaledhosny** [comment]
Yes, sorry. It does **not** work with Glyphs 2 for me.

**Comment by khaledhosny** [comment]
I installed pyobjc using pip2 but no luck (I didn’t find the Glyphs 2 tutorial).

**Comment by khaledhosny** [comment]
@simoncozens can you make glyphs3 the default branch? This seems to be the safest option. I‘ll then merge existing changes in master to glyphs3 branch.

**Pull request closed without merging**
